export default [
  {
    bg: 'silver',
    color: 'grey',
    category: 'Ingredients',
    subCategories: ['Chicken, Rice, Spice etc.'],
  },
  // {
  //   bg: '#086E4B',
  //   color: '#FCBE4A',
  //   category: 'Food & Drink',
  //   subCategories: [
  //     'Fruits & Vegetables',
  //     'Frozen Food',
  //     'Bakery',
  //     'Snacks & Desserts',
  //     'Beverages',
  //     'Alcoholic beverages',
  //     'Noodles & Pasta',
  //     'Rice & Cooking oil',
  //   ],
  // },
  {
    bg: 'silver',
    color: 'grey',
    category: 'Quantity',
    subCategories: ['200 Grams'],
  },
  {
    bg: 'silver',
    color: 'grey',
    category: 'Calories',
    subCategories: ['145 kcal'],
  },
  // {
  //   bg: '#193B8C',
  //   color: '#FECBCD',
  //   category: 'Baby & Kids',
  //   subCategories: [
  //     'Toys',
  //     'Trolleys',
  //     'LEGO®',
  //     'Electronics',
  //     'Puzzles',
  //     'Costumes',
  //     'Food',
  //     'Hygiene & Care',
  //     "Child's room",
  //     'Feeding accessories',
  //   ],
  // },
  // {
  //   bg: '#FDBD50',
  //   color: '#F5F5EB',
  //   category: 'Homeware',
  //   subCategories: [
  //     'Air purifiers',
  //     'Stoves, hoods & ovens',
  //     'Refrigerators',
  //     'Coffee & Tea',
  //     'Air conditioning',
  //     'Grilling',
  //     'Vacuum cleaners',
  //   ],
  // },
];